pub fn create_exceptions() -> String {
  r#"// AUTO GENERATED FILE, DO NOT EDIT
//
// Generated by `membrane`
abstract class MembraneException implements Exception {
  final String? message;

  const MembraneException(this.message);

  @override
  String toString() {
    {
      return (message == null) ? "$runtimeType" : "$runtimeType: $message";
    }
  }
}

class MembraneCancellationFailedException extends MembraneException {
  const MembraneCancellationFailedException([String? message]) : super(message);
}

class MembraneMemoryFreeFailedException extends MembraneException {
  const MembraneMemoryFreeFailedException([String? message]) : super(message);
}

class MembraneRustPanicException extends MembraneException {
  const MembraneRustPanicException([String? message]) : super(message);
}

class MembraneUnknownResponseVariantException extends MembraneException {
  const MembraneUnknownResponseVariantException([String? message]) : super(message);
}
"#
  .to_string()
}
