name: Clippy & Format

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: clippy and rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings -A clippy::uninlined_format_args
